### PR TITLE
Allowed tags made public

### PR DESCRIPTION
**Pull request by martonarbocz**
So we can add some validation to them in the shared gem

### CODE REVIEW

**Comment by hieuk09** [comment]
Could you explain your usage here? Is it used for test?

**Comment by martonarbocz** [comment]
I want to check in reporting if a given tag is allowed or not. There were bugs stemming from giving invalid tags to metrics.

**Comment by hieuk09** [comment]
@martonarbocz v0.4.3 is released which should support this.

**Comment by martonarbocz** [comment]
Okay, thanks!

**Pull request closed without merging**
